# Generated by Django 5.2.4 on 2025-07-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_rename_data_note_content_rename_date_note_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
