# Generated by Django 5.2.4 on 2025-09-01 19:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_note_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('title', 'owner')},
        ),
    ]
