# Generated by Django 5.2.4 on 2025-09-01 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_note_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('title', 'owner')},
        ),
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('slug', 'owner'), ('title', 'owner')},
        ),
    ]
